import { test, describe } from "node:test";
import assert from "node:assert/strict";
import { renderPrd } from "../dist/render-prd.js";
import { validSpec, minimalValidSpec, clone } from "./fixtures.mjs";

describe("renderPrd - top-level structure", () => {
  test("contains title and byline", () => {
    const md = renderPrd(validSpec());
    assert.match(md, /# TaskFlow/);
    assert.match(md, /_Spec generated by draftlytic-mcp_/);
  });

  test("section headings appear in the expected order", () => {
    const md = renderPrd(validSpec());
    const headings = [
      "## Overview",
      "## Target Audience",
      "## Platforms",
      "## Tech Stack",
      "## Features",
      "## Constraints",
      "## Non-Goals",
      "## Revenue Model",
    ];
    const indexes = headings.map((h) => md.indexOf(h));
    for (const [i, idx] of indexes.entries()) {
      assert.notEqual(idx, -1, `expected to find heading: ${headings[i]}`);
    }
    for (let i = 1; i < indexes.length; i++) {
      assert.ok(
        indexes[i - 1] < indexes[i],
        `expected "${headings[i - 1]}" (at ${indexes[i - 1]}) to come before "${headings[i]}" (at ${indexes[i]})`,
      );
    }
  });

  test("title uses spec.name is placed before Overview section", () => {
    const spec = clone(validSpec());
    spec.name = "MyApp";
    const md = renderPrd(spec);
    assert.ok(md.startsWith("# MyApp\n"));
    assert.ok(md.indexOf("# MyApp") < md.indexOf("## Overview"));
  });

  test("overview and target_audience text appear under their headings", () => {
    const md = renderPrd(validSpec());
    assert.match(
      md,
      /## Overview\n\nA lightweight kanban board for solo developers to track side projects\./,
    );
    assert.match(
      md,
      /## Target Audience\n\nIndie developers juggling multiple side projects\./,
    );
  });
});

describe("renderPrd - features grouped by priority", () => {
  test("all three groups render in order must-have -> nice-to-have -> future", () => {
    const md = renderPrd(validSpec());
    const mustIdx = md.indexOf("### Must Have");
    const niceIdx = md.indexOf("### Nice to Have");
    const futureIdx = md.indexOf("### Future");
    assert.notEqual(mustIdx, -1);
    assert.notEqual(niceIdx, -1);
    assert.notEqual(futureIdx, -1);
    assert.ok(mustIdx < niceIdx);
    assert.ok(niceIdx < futureIdx);
  });

  test("numbering resets per group starting at #### 1.", () => {
    const md = renderPrd(validSpec());
    // Must Have group's first (and only) feature is numbered 1.
    assert.match(md, /### Must Have\n\n#### 1\. Drag-and-drop board/);
    // Nice to Have group's first feature also numbered 1.
    assert.match(md, /### Nice to Have\n\n#### 1\. Dark mode/);
    // Future group's first feature also numbered 1.
    assert.match(md, /### Future\n\n#### 1\. Mobile app/);
  });

  test("numbering increments within a group with multiple features of same priority", () => {
    const spec = clone(minimalValidSpec());
    spec.features = [
      { title: "First", description: "d1", priority: "must-have" },
      { title: "Second", description: "d2", priority: "must-have" },
      { title: "Third", description: "d3", priority: "must-have" },
    ];
    const md = renderPrd(spec);
    assert.match(md, /#### 1\. First/);
    assert.match(md, /#### 2\. Second/);
    assert.match(md, /#### 3\. Third/);
  });

  test("a priority group with zero features is omitted entirely", () => {
    const spec = clone(validSpec());
    spec.features = spec.features.filter((f) => f.priority !== "future");
    const md = renderPrd(spec);
    assert.ok(!md.includes("### Future"));
    assert.ok(md.includes("### Must Have"));
    assert.ok(md.includes("### Nice to Have"));
  });

  test("only must-have present -> only that subheading appears", () => {
    const spec = clone(minimalValidSpec());
    spec.features = [
      { title: "Solo", description: "Only feature.", priority: "must-have" },
    ];
    const md = renderPrd(spec);
    assert.ok(md.includes("### Must Have"));
    assert.ok(!md.includes("### Nice to Have"));
    assert.ok(!md.includes("### Future"));
  });

  test("feature description text is rendered under the numbered heading", () => {
    const md = renderPrd(validSpec());
    assert.match(
      md,
      /#### 1\. Drag-and-drop board\n\nMove cards between columns to update status\./,
    );
  });
});

describe("renderPrd - acceptance criteria", () => {
  test("renders as a checklist under '**Acceptance criteria:**'", () => {
    const md = renderPrd(validSpec());
    assert.match(
      md,
      /\*\*Acceptance criteria:\*\*\n\n- \[ \] Cards can be dragged between columns\n- \[ \] Column order persists across reloads/,
    );
  });

  test("a feature without acceptance_criteria has no such block", () => {
    const spec = clone(minimalValidSpec());
    spec.features = [
      { title: "No AC", description: "Has no acceptance criteria.", priority: "must-have" },
    ];
    const md = renderPrd(spec);
    assert.ok(!md.includes("**Acceptance criteria:**"));
  });

  test("a feature with an empty acceptance_criteria array has no such block", () => {
    const spec = clone(minimalValidSpec());
    spec.features = [
      {
        title: "Empty AC",
        description: "Has empty acceptance criteria array.",
        priority: "must-have",
        acceptance_criteria: [],
      },
    ];
    const md = renderPrd(spec);
    assert.ok(!md.includes("**Acceptance criteria:**"));
  });
});

describe("renderPrd - screens", () => {
  test("renders '## Screens & Navigation' with a table when screens present", () => {
    const md = renderPrd(validSpec());
    assert.match(md, /## Screens & Navigation\n\n\| Screen \| Purpose \|\n\|:--\|:--\|/);
    assert.match(md, /\| \*\*Board\*\* \| The main kanban view with columns\. \|/);
    assert.match(md, /\| \*\*Settings\*\* \| Theme and account preferences\. \|/);
  });

  test("no screens section when screens is absent", () => {
    const spec = clone(minimalValidSpec());
    delete spec.screens;
    const md = renderPrd(spec);
    assert.ok(!md.includes("## Screens & Navigation"));
  });

  test("no screens section when screens is an empty array", () => {
    const spec = clone(validSpec());
    spec.screens = [];
    const md = renderPrd(spec);
    assert.ok(!md.includes("## Screens & Navigation"));
  });
});

describe("renderPrd - data model", () => {
  test("renders '## Data Model' with entity heading and table when present", () => {
    const md = renderPrd(validSpec());
    assert.match(md, /## Data Model\n\n#### Card\n\n\| Field \| Type \| Notes \|\n\|:--\|:--\|:--\|/);
    assert.match(md, /\| `id` \| uuid \| primary key \|/);
    assert.match(md, /\| `title` \| text \|  \|/); // no notes -> empty cell
  });

  test("no data model section when data_model is absent", () => {
    const spec = clone(minimalValidSpec());
    delete spec.data_model;
    const md = renderPrd(spec);
    assert.ok(!md.includes("## Data Model"));
  });

  test("no data model section when data_model is an empty array", () => {
    const spec = clone(validSpec());
    spec.data_model = [];
    const md = renderPrd(spec);
    assert.ok(!md.includes("## Data Model"));
  });

  test("field name is wrapped in backticks", () => {
    const md = renderPrd(validSpec());
    assert.match(md, /\| `column_id` \| uuid \| foreign key to Column \|/);
  });

  test("a field with no notes renders an empty notes cell", () => {
    const spec = clone(minimalValidSpec());
    spec.data_model = [
      { entity: "Thing", fields: [{ name: "id", type: "uuid" }] },
    ];
    const md = renderPrd(spec);
    assert.match(md, /\| `id` \| uuid \|  \|/);
  });

  test("an entity with an empty fields array renders '_No fields defined._' not a table", () => {
    const spec = clone(minimalValidSpec());
    spec.data_model = [{ entity: "Empty", fields: [] }];
    const md = renderPrd(spec);
    assert.match(md, /#### Empty\n\n_No fields defined\._/);
    assert.ok(!md.includes("| Field | Type | Notes |"));
  });

  test("multiple entities each render their own block", () => {
    const md = renderPrd(validSpec());
    assert.match(md, /#### Card/);
    assert.match(md, /#### Column/);
    assert.ok(md.indexOf("#### Card") < md.indexOf("#### Column"));
  });
});

describe("renderPrd - renderList behavior (Platforms/Tech Stack/Constraints/Non-Goals)", () => {
  test("items render as '- item' bullets", () => {
    const md = renderPrd(validSpec());
    assert.match(md, /## Platforms\n\n- web/);
    assert.match(md, /## Tech Stack\n\n- TypeScript\n- React\n- Supabase/);
    assert.match(md, /## Constraints\n\n- Must run on free-tier Supabase\./);
    assert.match(md, /## Non-Goals\n\n- No team or multi-user support in v1\./);
  });

  test("empty tech_stack array renders '_None specified._'", () => {
    const md = renderPrd(minimalValidSpec());
    assert.match(md, /## Tech Stack\n\n_None specified\._/);
  });

  test("absent constraints/non_goals renders '_None specified._'", () => {
    const md = renderPrd(minimalValidSpec());
    assert.match(md, /## Constraints\n\n_None specified\._/);
    assert.match(md, /## Non-Goals\n\n_None specified\._/);
  });

  test("empty (but present) constraints array renders '_None specified._'", () => {
    const spec = clone(validSpec());
    spec.constraints = [];
    const md = renderPrd(spec);
    assert.match(md, /## Constraints\n\n_None specified\._/);
  });
});

describe("renderPrd - revenue model", () => {
  test("absent revenue_model renders '_None specified._'", () => {
    const md = renderPrd(minimalValidSpec());
    assert.match(md, /## Revenue Model\n\n_None specified\._/);
  });

  test("empty string revenue_model renders '_None specified._' (falsy)", () => {
    const spec = clone(validSpec());
    spec.revenue_model = "";
    const md = renderPrd(spec);
    assert.match(md, /## Revenue Model\n\n_None specified\._/);
  });

  test("present revenue_model renders the text", () => {
    const md = renderPrd(validSpec());
    assert.match(
      md,
      /## Revenue Model\n\nFree with a paid pro tier for unlimited boards\./,
    );
  });
});

describe("renderPrd - escapeCell", () => {
  test("pipes in screen name/purpose are escaped and newlines collapse", () => {
    const spec = clone(validSpec());
    spec.screens = [
      { name: "Weird | Screen\nName", purpose: "Does A | B\r\nand C\rD" },
    ];
    const md = renderPrd(spec);
    // Find the rendered row.
    const rowMatch = md.match(/\| \*\*(.+?)\*\* \| (.+?) \|\n/);
    assert.ok(rowMatch, "expected to find a screens table row");
    // Raw newline must not appear inside the cell content (row is a single line).
    assert.ok(!rowMatch[0].includes("\r"));
    // Pipe must be escaped, not raw within the cell text.
    assert.ok(rowMatch[1].includes("Weird \\| Screen Name"));
    assert.ok(rowMatch[2].includes("Does A \\| B and C D"));
    // The escaped pipe should NOT be interpretable as a raw column-separator pipe.
    assert.ok(!/Weird \|(?!\\) Screen/.test(md.replace(/\\\|/g, "")));
  });

  test("pipes and newlines in data model entity/field name/type/notes are escaped", () => {
    const spec = clone(validSpec());
    spec.data_model = [
      {
        entity: "Weird | Entity\nName",
        fields: [
          {
            name: "field | name\nhere",
            type: "type | here\r\nmulti",
            notes: "notes\rwith | pipe",
          },
        ],
      },
    ];
    const md = renderPrd(spec);
    const dataModelSection = md.slice(md.indexOf("## Data Model"));

    // Entity heading line.
    const headingMatch = dataModelSection.match(/#### (.+)\n/);
    assert.ok(headingMatch);
    assert.equal(headingMatch[1], "Weird \\| Entity Name");
    assert.ok(!headingMatch[0].includes("\n\n")); // single collapsed line before trailing \n

    // Field row.
    const rowMatch = dataModelSection.match(/\| `(.+?)` \| (.+?) \| (.+?) \|\n/);
    assert.ok(rowMatch, "expected to find a data model table row");
    assert.equal(rowMatch[1], "field \\| name here");
    assert.equal(rowMatch[2], "type \\| here multi");
    assert.equal(rowMatch[3], "notes with \\| pipe");

    // No raw \r remains anywhere.
    assert.ok(!md.includes("\r"));
  });

  test("the table row count matches number of screens even with embedded newlines", () => {
    const spec = clone(validSpec());
    spec.screens = [
      { name: "A\nB", purpose: "C\nD" },
      { name: "E", purpose: "F" },
    ];
    const md = renderPrd(spec);
    const section = md.slice(md.indexOf("## Screens & Navigation"));
    const lines = section.split("\n").filter((l) => l.startsWith("| **"));
    assert.equal(lines.length, 2);
  });
});

describe("renderPrd - determinism", () => {
  test("calling renderPrd twice on the same input yields identical strings", () => {
    const spec = validSpec();
    const first = renderPrd(clone(spec));
    const second = renderPrd(clone(spec));
    assert.equal(first, second);
  });

  test("determinism holds for minimalValidSpec too", () => {
    const spec = minimalValidSpec();
    const first = renderPrd(clone(spec));
    const second = renderPrd(clone(spec));
    assert.equal(first, second);
  });
});

describe("renderPrd - minimal spec smoke", () => {
  test("renders without throwing and includes all headings even with mostly-empty optional fields", () => {
    const md = renderPrd(minimalValidSpec());
    assert.match(md, /# Minimal/);
    assert.match(md, /## Overview\n\nA tiny valid spec\./);
    assert.match(md, /## Target Audience\n\nTesters\./);
    assert.match(md, /## Platforms\n\n- web/);
    assert.match(md, /## Tech Stack\n\n_None specified\._/);
    assert.match(md, /### Must Have\n\n#### 1\. Core thing/);
    assert.ok(!md.includes("## Screens & Navigation"));
    assert.ok(!md.includes("## Data Model"));
    assert.match(md, /## Constraints\n\n_None specified\._/);
    assert.match(md, /## Non-Goals\n\n_None specified\._/);
    assert.match(md, /## Revenue Model\n\n_None specified\._/);
  });
});
