/**
 * render_prd — deterministic Markdown renderer for a Spec.
 *
 * Section order and grouping mirror the spirit of how Draftlytic's own PRD
 * export reads (overview up top, features grouped by priority with
 * acceptance-criteria checklists, then screens/data model, then constraints
 * and business context at the end) — hand-written for this package, not a
 * port of Draftlytic's renderer.
 */
import type { Spec, Feature, FeaturePriority } from "./spec-schema.js";

const PRIORITY_LABELS: Record<FeaturePriority, string> = {
  "must-have": "Must Have",
  "nice-to-have": "Nice to Have",
  future: "Future",
};

const PRIORITY_ORDER: FeaturePriority[] = [
  "must-have",
  "nice-to-have",
  "future",
];

/**
 * Escape a value before interpolating it into a Markdown table cell.
 * A literal "|" would be parsed as a new column boundary, and a raw
 * newline would break the row onto multiple lines — both corrupt the
 * table. Collapse newlines to a single space and escape pipes.
 */
function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\r\n|\r|\n/g, " ");
}

function renderList(items: string[] | undefined): string {
  if (!items || items.length === 0) return "_None specified._\n";
  return items.map((item) => `- ${item}`).join("\n") + "\n";
}

function renderFeaturesByPriority(features: Feature[]): string {
  const groups: Record<FeaturePriority, Feature[]> = {
    "must-have": [],
    "nice-to-have": [],
    future: [],
  };
  for (const f of features) {
    groups[f.priority].push(f);
  }

  const blocks: string[] = [];
  for (const priority of PRIORITY_ORDER) {
    const items = groups[priority];
    if (items.length === 0) continue;
    blocks.push(`### ${PRIORITY_LABELS[priority]}\n`);
    const rendered = items.map((f, i) => {
      const lines = [`#### ${i + 1}. ${f.title}\n`, `${f.description}`];
      if (f.acceptance_criteria && f.acceptance_criteria.length > 0) {
        lines.push("\n**Acceptance criteria:**\n");
        lines.push(f.acceptance_criteria.map((ac) => `- [ ] ${ac}`).join("\n"));
      }
      return lines.join("\n");
    });
    blocks.push(rendered.join("\n\n") + "\n");
  }

  return blocks.length > 0 ? blocks.join("\n") : "_No features defined._\n";
}

function renderDataModel(spec: Spec): string {
  if (!spec.data_model || spec.data_model.length === 0) return "";
  const blocks = spec.data_model.map((entity) => {
    const lines = [`#### ${escapeCell(entity.entity)}\n`];
    if (entity.fields.length === 0) {
      lines.push("_No fields defined._");
    } else {
      lines.push("| Field | Type | Notes |");
      lines.push("|:--|:--|:--|");
      for (const field of entity.fields) {
        const name = escapeCell(field.name);
        const type = escapeCell(field.type);
        const notes = escapeCell(field.notes ?? "");
        lines.push(`| \`${name}\` | ${type} | ${notes} |`);
      }
    }
    return lines.join("\n");
  });
  return `## Data Model\n\n${blocks.join("\n\n")}\n`;
}

function renderScreens(spec: Spec): string {
  if (!spec.screens || spec.screens.length === 0) return "";
  const rows = spec.screens
    .map((s) => `| **${escapeCell(s.name)}** | ${escapeCell(s.purpose)} |`)
    .join("\n");
  return (
    `## Screens & Navigation\n\n` +
    `| Screen | Purpose |\n` +
    `|:--|:--|\n` +
    `${rows}\n`
  );
}

export function renderPrd(spec: Spec): string {
  const lines: string[] = [];

  lines.push(`# ${spec.name}\n`);
  lines.push(`_Spec generated by draftlytic-mcp_\n`);

  lines.push(`## Overview\n`);
  lines.push(`${spec.overview}\n`);

  lines.push(`## Target Audience\n`);
  lines.push(`${spec.target_audience}\n`);

  lines.push(`## Platforms\n`);
  lines.push(renderList(spec.platforms));

  lines.push(`## Tech Stack\n`);
  lines.push(renderList(spec.tech_stack));

  lines.push(`## Features\n`);
  lines.push(renderFeaturesByPriority(spec.features));

  const screens = renderScreens(spec);
  if (screens) lines.push(screens);

  const dataModel = renderDataModel(spec);
  if (dataModel) lines.push(dataModel);

  lines.push(`## Constraints\n`);
  lines.push(renderList(spec.constraints));

  lines.push(`## Non-Goals\n`);
  lines.push(renderList(spec.non_goals));

  lines.push(`## Revenue Model\n`);
  lines.push(
    spec.revenue_model ? `${spec.revenue_model}\n` : "_None specified._\n",
  );

  return lines.join("\n");
}
